import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import React, { ReactNode, useEffect, useState, FunctionComponent } from 'react';
import GlobalToastProvider from '@/components/GlobalToastProvider';
import GlobalErrorProvider from '@/components/GlobalErrorProvider';
import '@/styles/globals.css'
import '@/styles/xterm.css'
import { PasswordLessCard } from '@/lib/models';
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

          {children}
        </Providers>

      </body>

    </html>
  );
}
