#pragma once

static const char *TAG = "keydot";

#define MAX_PASS_SIZE 50
#define MAX_DESC_SIZE 50
#define NVS_STORAGE_NAMESPACE "kb"

#define TRIGGER_BUTTON_PIN GPIO_NUM_39
#define TRIGGER_BUTTON_BIT_MASK (1ULL << TRIGGER_BUTTON_PIN)

#define LED_PIN GPIO_NUM_18
#define SOLID_COLOR_DUTY 4000

// #define STATE_PRINT_INTERVAL_US 5 * 1000 * 1000
#define STATE_PRINT_INTERVAL_US 50 * 1000
#define MAIN_LOOP_INTERVAL_MS 100
// #define MAIN_LOOP_INTERVAL_MS 10

#define SCANNED_CARD_EXPIRY_MS 5000

// #define LOG_DETAILS
